import 'package:finitepay/controllers/init_controllers.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
// import 'package:flutter/widgets.dart';


final ScrollController scrollController = ScrollController();

List<Widget> dashtransacElements = [
  const Card(
    // color: Colors.greenAccent,
    child: Padding(
      padding: EdgeInsets.all(8.0),
      child: Column(
        children: [
          Text(
            'Awaiting Funds',
            style: TextStyle(overflow: TextOverflow.ellipsis),
          ),
          Divider(),
          Expanded(child: Center(child: Text('0'))),
        ],
      ),
    ),
  ),
  const Card(
    // color: Colors.red,
    child: Padding(
      padding: EdgeInsets.all(8.0),
      child: Column(
        children: [
          Text(
            'Failed Payments',
            style: TextStyle(overflow: TextOverflow.ellipsis),
          ),
          Divider(),
          Expanded(child: Center(child: Text('0'))),
        ],
      ),
    ),
  ),
  const Card(
    // color: Colors.blue,
    child: Padding(
      padding: EdgeInsets.all(8.0),
      child: Column(
        children: [
          Text(
            'Fx Conversions Today',
            style: TextStyle(overflow: TextOverflow.ellipsis),
          ),
          Divider(),
          Expanded(child: Center(child: Text('0'))),
        ],
      ),
    ),
  ),
  Card(
    // color: Colors.blue,
    child: Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        children: [
          const Text(
            'Pending transactions',
            style: TextStyle(overflow: TextOverflow.ellipsis),
          ),
          const Divider(),
          Expanded(
            child: Center(
              child: Obx(
                () => Text(
                  currencyCloudController
                          .transactionsObject.value?.transactions.length
                          .toString() ??
                      0.toString(),
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.red,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    ),
  ),
  const Card(
    // color: Colors.orange,
    child: Padding(
      padding: EdgeInsets.all(8.0),
      child: Column(
        children: [
          Text(
            'Complete  Transactions Today',
            style: TextStyle(overflow: TextOverflow.ellipsis),
          ),
          Divider(),
          Expanded(child: Center(child: Text('0'))),
        ],
      ),
    ),
  ),
  const Card(
    // color: Colors.green,
    child: Padding(
      padding: EdgeInsets.all(8.0),
      child: Column(
        children: [
          Text(
            'Complete Payments Today',
            style: TextStyle(overflow: TextOverflow.ellipsis),
          ),
          Divider(),
          Expanded(child: Center(child: Text('0'))),
        ],
      ),
    ),
  ),
];

final List<String> countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
