import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

final FirebaseAuth fAuth = FirebaseAuth.instance;

User? currentFirebaseUser;
User? user = FirebaseAuth.instance.currentUser;

BuildContext? loadingDialogContext;

Future<void> showLoading(String message) {
  return showDialog(
    context: Get.context!,
    barrierDismissible: false,
    builder: (BuildContext context) {
      loadingDialogContext = context;
      return AlertDialog(
        content: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            const CircularProgressIndicator(
              backgroundColor: Colors.greenAccent,
            ),
            Text(
              message,
              textAlign: TextAlign.center,
              style: const TextStyle(
                fontWeight: FontWeight.bold,
              ),
            )
          ],
        ),
      );
    },
  );
}
// THIS APPLIES FOR THE CASE OF BUSINESS  STARTS FROM THIS POINT..........

List<String> industries = [
  "HotelMotel",
  "OtherFoodServices",
  "Restaurants",
  "ArtPhotography",
  "ArtsEntertainment",
  "FitnessSportsCenters",
  "SportsTeamsClubs",
  "Construction",
  "BuildingMaterialsHardware",
  "OtherTradeContractor",
  "PlumbingHVAC",
  "HealthServices",
  "OtherEducationServices",
  "OtherHealthFitness",
  "AccountingTaxPrep",
  "RealEstate",
  "HomeFurnishing",
  "BeautyOrBarberShops",
  "CarWash",
  "ComputerServiceRepair",
  "FreelanceProfessional",
  "LandscapeServices",
  "LegalServices",
  "MassageTanningServices",
  "OtherProfessionalServices",
  "AutoDealers",
  "OnlineRetailer",
  "Retail",
  "GasolineServiceStation",
  "OtherTransportServices",
  "OtherTravelServices",
  "ParkingGarages",
  "Taxi",
  "TravelAgency",
  "TruckingShipping",
  "Wholesale",
  "WarehouseDistribution",
  "OtherAccomodations",
  "AnimalFarmingProduction",
  "CropFarming",
  "ForestryActivities",
  "FishingHuntingTrapping",
  "OtherAgricultureForestryFishing",
  "MuseumsHistoricalSites",
  "Hospitals",
  "CollegesUniversitiesSchools",
  "BankFinancialInstitution",
  "FinancialInvestments",
  "FundsTrustsOther",
  "Insurance",
  "MoneyTransferRemittance",
  "PrivateInvestmentCompanies",
  "OtherManufacturing",
  "IndustrialCommercialMachinery",
  "EmploymentServices",
  "GovernmentAgency",
  "NonGovernmentOrganization",
  "ReligiousOrganization",
  "Unions",
  "RetailJewelerDiamondsGemsGold",
  "RetailCash",
  "UsedClothesDealers",
  "TourOperator",
  "WholesaleJeweler",
];
List<String> businessTypes = [
  "SoleProprietor",
  "SingleMemberLLC",
  "LimitedLiabilityCompany",
  "GeneralPartnership",
  "UnlistedCorporation",
  "PubliclyTradedCorporation",
  "Association",
  "NonProfit",
  "GovernmentOrganization",
  "RevocableTrust",
  "IrrevocableTrust",
  "Estate",
  "LimitedPartnership",
  "LimitedLiabilityPartnership",
];


// THIS APPLIES FOR THE CASE OF BUSINESS ENDS HERE..............


final List<String> incomeRange = [
  "200000",
  "500000",
  "1000000",
  "2000000",
  "3000000"
];

final List<String> employmentStatus = [
  "employed",
  "unemployed",
  "self_employed",
];



final List<String> occupations = [
  'Accountant',
  'Actor',
  'Architect',
  'Artist',
  'Attorney',
  'Banker',
  'Barber',
  'Bartender',
  'Biologist',
  'Carpenter',
  'Cashier',
  'Chef',
  'Chemist',
  'Coach',
  'Consultant',
  'Dentist',
  'Designer',
  'Developer',
  'Doctor',
  'Driver',
  'Economist',
  'Electrician',
  'Engineer',
  'Farmer',
  'Firefighter',
  'Geologist',
  'Hairdresser',
  'Journalist',
  'Lawyer',
  'Librarian',
  'Mechanic',
  'Musician',
  'Nurse',
  'Optician',
  'Pharmacist',
  'Photographer',
  'Physicist',
  'Pilot',
  'Plumber',
  'Police Officer',
  'Professor',
  'Psychologist',
  'Realtor',
  'Researcher',
  'Salesperson',
  'Scientist',
  'Secretary',
  'Soldier',
  'Surgeon',
  'Teacher',
  'Technician',
  'Therapist',
  'Translator',
  'Veterinarian',
  'Waiter',
  'Writer',
];

final List<String> incomeList = [
  'Salary',
  'Business',
  'Freelance',
  'Rental Income',
  'Investments',
  'Dividends',
  'Royalties',
  'Pensions',
  'Social Security',
  'Alimony',
  'Child Support',
  'Scholarships',
  'Grants',
  'Inheritance',
  'Bonuses',
  'Commissions',
  'Interest',
  'Side Hustle',
  'Government Assistance',
  'Annuities',
  'Trust Fund',
  'Stock Options',
  'Capital Gains',
  'Tips',
  'Gifts',
  'Partnerships',
  'Stipends',
  'Settlements',
  'Lottery Winnings',
  'Crowdfunding',
  'Other',
];

final List<String> accountDesignations = [
  'Personal Use',
  'Corporate',
  'Savings',
  'Checking',
  'Joint Account',
  'Trust Account',
  'Retirement Account',
  'Business Account',
  'Student Account',
  'Payroll Account',
  'Loan Repayment',
  'Investment Account',
  'Expense Account',
  'Escrow Account',
  'Charitable Account',
  'Foreign Currency',
  'Tax Account',
  'Petty Cash Account',
  'Mortgage Account',
  'Reserve Account',
];

// List of company types
final List<String> companyTypes = [
  'Sole Proprietorship',
  'Partnership',
  'Limited Liability Company (LLC)',
  'Corporation',
  'Non-Profit Organization',
  'Cooperative',
  'Limited Partnership (LP)',
  'Joint Venture',
  'S Corporation',
  'C Corporation',
];

// List of business models
final List<String> businessModels = [
  'Business-to-Business (B2B)',
  'Business-to-Consumer (B2C)',
  'Consumer-to-Consumer (C2C)',
  'Consumer-to-Business (C2B)',
  'Business-to-Government (B2G)',
  'Government-to-Business (G2B)',
  'Peer-to-Peer (P2P)',
  'Direct-to-Consumer (D2C)',
  'Franchise Model',
  'Subscription Model',
  'Freemium Model',
  'On-Demand Model',
  'Aggregator Model',
  'Marketplace Model',
];

List<String> currenciesAvailable = [
  'USD',
  'ZAR',
  'EUR',
  'KES',
  'AUD',
  'CAD',
  'CNY',
  'UGX',
];

Map<String, dynamic> flagsmap = {
  'USD':
      'https://avatars.mds.yandex.net/i?id=65c6bfb32fb835e8a5a3478d02d4e9cb35d0e671-9263520-images-thumbs&n=13',
  'ZAR':
      'https://avatars.mds.yandex.net/i?id=0ae6ee9fd2b74bc73e38d77f3ceb6344aef8723f-5320725-images-thumbs&n=13',
  'EUR':
      'https://avatars.mds.yandex.net/i?id=af879092d7b5f96ee9ebe71e72e68d26166b9513-8253234-images-thumbs&n=13',
  'KES':
      'https://avatars.mds.yandex.net/i?id=2d5b9bb3eb41a38ece4086973a01a170f0feb1ec-7086266-images-thumbs&n=13',
  'AUD':
      'https://avatars.mds.yandex.net/i?id=63662b01f8f563e9a8f030ead7d5b5f6b7d918fe-8224882-images-thumbs&n=13',
  'CAD':
      'https://avatars.mds.yandex.net/i?id=a2227502b99ea2fba16897ac2d959ca01b7e106a-5874919-images-thumbs&n=13',
  'CNY':
      'https://avatars.mds.yandex.net/i?id=1761df1bff153dee8697448949f3390bb595f2e6-12727346-images-thumbs&n=13',
  'UGX':
      'https://avatars.mds.yandex.net/i?id=663ba7ea23414bd92ce56c7cbeb864bf80304f03-7066306-images-thumbs&n=13'
};

List flags = [
  'https://avatars.mds.yandex.net/i?id=65c6bfb32fb835e8a5a3478d02d4e9cb35d0e671-9263520-images-thumbs&n=13',
  'https://avatars.mds.yandex.net/i?id=0ae6ee9fd2b74bc73e38d77f3ceb6344aef8723f-5320725-images-thumbs&n=13',
  'https://avatars.mds.yandex.net/i?id=af879092d7b5f96ee9ebe71e72e68d26166b9513-8253234-images-thumbs&n=13',
  'https://avatars.mds.yandex.net/i?id=2d5b9bb3eb41a38ece4086973a01a170f0feb1ec-7086266-images-thumbs&n=13',
  'https://avatars.mds.yandex.net/i?id=63662b01f8f563e9a8f030ead7d5b5f6b7d918fe-8224882-images-thumbs&n=13',
  'https://avatars.mds.yandex.net/i?id=a2227502b99ea2fba16897ac2d959ca01b7e106a-5874919-images-thumbs&n=13',
  'https://avatars.mds.yandex.net/i?id=1761df1bff153dee8697448949f3390bb595f2e6-12727346-images-thumbs&n=13',
  'https://avatars.mds.yandex.net/i?id=663ba7ea23414bd92ce56c7cbeb864bf80304f03-7066306-images-thumbs&n=13'
];

List registrationOptions = [
  'individual',
  'company',
];
// List identifiedBy = ['incorporation_number', 'national_id',  'driving_licence'];
const List<String> subaccountIdentificationOptions = [
  "national_id",
  "incorporation_number",
  "drivers_license",
  "social_security_number",
  "green_card",
  "passport",
  "visa",
  "matricula_consular",
  "registro_federal_de_contribuyentes",
  "clave_unica_de_registro_de_poblacion",
  "credential_de_elector",
  "social_insurance_number",
  "citizenship_papers",
  "drivers_license_canadian",
  "existing_credit_card_details",
  "employer_identification_number",

  // "incorporation_number",
  // "lei",                  // Legal Entity Identifier
  // "ein",                  // Employer Identification Number
  // "vat_number",           // Value Added Tax Number
  // "company_registration_number",
  // "duns_number",          // Data Universal Numbering System
  // "passport_number",
  // "national_id_number",
  // "tax_identification_number",
  // "business_license_number",
  // "trade_registry_number"
];

const Map<String, String> countryCodes = {
  "Afghanistan": "AF",
  "Albania": "AL",
  "Algeria": "DZ",
  "Andorra": "AD",
  "Angola": "AO",
  "Antigua and Barbuda": "AG",
  "Argentina": "AR",
  "Armenia": "AM",
  "Australia": "AU",
  "Austria": "AT",
  "Azerbaijan": "AZ",
  "Bahamas": "BS",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Barbados": "BB",
  "Belarus": "BY",
  "Belgium": "BE",
  "Belize": "BZ",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Bolivia": "BO",
  "Bosnia and Herzegovina": "BA",
  "Botswana": "BW",
  "Brazil": "BR",
  "Brunei": "BN",
  "Bulgaria": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cabo Verde": "CV",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Canada": "CA",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Chile": "CL",
  "China": "CN",
  "Colombia": "CO",
  "Comoros": "KM",
  "Congo, Democratic Republic of the": "CD",
  "Congo, Republic of the": "CG",
  "Costa Rica": "CR",
  "Cote d'Ivoire": "CI",
  "Croatia": "HR",
  "Cuba": "CU",
  "Cyprus": "CY",
  "Czech Republic": "CZ",
  "Denmark": "DK",
  "Djibouti": "DJ",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "Ecuador": "EC",
  "Egypt": "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Estonia": "EE",
  "Eswatini": "SZ",
  "Ethiopia": "ET",
  "Fiji": "FJ",
  "Finland": "FI",
  "France": "FR",
  "Gabon": "GA",
  "Gambia": "GM",
  "Georgia": "GE",
  "Germany": "DE",
  "Ghana": "GH",
  "Greece": "GR",
  "Grenada": "GD",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Guyana": "GY",
  "Haiti": "HT",
  "Honduras": "HN",
  "Hungary": "HU",
  "Iceland": "IS",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Iraq": "IQ",
  "Ireland": "IE",
  "Israel": "IL",
  "Italy": "IT",
  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kiribati": "KI",
  "Korea, North": "KP",
  "Korea, South": "KR",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",
  "Laos": "LA",
  "Latvia": "LV",
  "Lebanon": "LB",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Libya": "LY",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Mali": "ML",
  "Malta": "MT",
  "Marshall Islands": "MH",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Mexico": "MX",
  "Micronesia": "FM",
  "Moldova": "MD",
  "Monaco": "MC",
  "Mongolia": "MN",
  "Montenegro": "ME",
  "Morocco": "MA",
  "Mozambique": "MZ",
  "Myanmar": "MM",
  "Namibia": "NA",
  "Nauru": "NR",
  "Nepal": "NP",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "North Macedonia": "MK",
  "Norway": "NO",
  "Oman": "OM",
  "Pakistan": "PK",
  "Palau": "PW",
  "Panama": "PA",
  "Papua New Guinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Poland": "PL",
  "Portugal": "PT",
  "Qatar": "QA",
  "Romania": "RO",
  "Russia": "RU",
  "Rwanda": "RW",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Samoa": "WS",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Saudi Arabia": "SA",
  "Senegal": "SN",
  "Serbia": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Singapore": "SG",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Solomon Islands": "SB",
  "Somalia": "SO",
  "South Africa": "ZA",
  "South Sudan": "SS",
  "Spain": "ES",
  "Sri Lanka": "LK",
  "Sudan": "SD",
  "Suriname": "SR",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Syria": "SY",
  "Taiwan": "TW",
  "Tajikistan": "TJ",
  "Tanzania": "TZ",
  "Thailand": "TH",
  "Timor-Leste": "TL",
  "Togo": "TG",
  "Tonga": "TO",
  "Trinidad and Tobago": "TT",
  "Tunisia": "TN",
  "Turkey": "TR",
  "Turkmenistan": "TM",
  "Tuvalu": "TV",
  "Uganda": "UG",
  "Ukraine": "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  "Uruguay": "UY",
  "Uzbekistan": "UZ",
  "Vanuatu": "VU",
  "Vatican City": "VA",
  "Venezuela": "VE",
  "Vietnam": "VN",
  "Yemen": "YE",
  "Zambia": "ZM",
  "Zimbabwe": "ZW"
};
