// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9PO1QnXeqB1N8LDpDauMpaUvN1RMIshs',
    appId: '1:649781205611:web:c86798b0cf503100faaf2e',
    messagingSenderId: '649781205611',
    projectId: 'mpesa-flutter',
    authDomain: 'mpesa-flutter.firebaseapp.com',
    databaseURL: 'https://mpesa-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'mpesa-flutter.appspot.com',
    measurementId: 'G-FSKE4B3GT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFRPaoz9jPn96H0oUX2ZBtsaG7rhSXKsc',
    appId: '1:649781205611:android:05a27e32beb605ddfaaf2e',
    messagingSenderId: '649781205611',
    projectId: 'mpesa-flutter',
    databaseURL: 'https://mpesa-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'mpesa-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNhF4-EBvEgmvH2kMjZvcYAT-Okn9uHDc',
    appId: '1:649781205611:ios:f71b3020b6042596faaf2e',
    messagingSenderId: '649781205611',
    projectId: 'mpesa-flutter',
    databaseURL: 'https://mpesa-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'mpesa-flutter.appspot.com',
    iosBundleId: 'com.example.finitepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNhF4-EBvEgmvH2kMjZvcYAT-Okn9uHDc',
    appId: '1:649781205611:ios:f71b3020b6042596faaf2e',
    messagingSenderId: '649781205611',
    projectId: 'mpesa-flutter',
    databaseURL: 'https://mpesa-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'mpesa-flutter.appspot.com',
    iosBundleId: 'com.example.finitepay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnybXmMuLcJ38z_eNi3rWElm1umJJS9c8',
    appId: '1:649781205611:web:f3370711f93777fbfaaf2e',
    messagingSenderId: '649781205611',
    projectId: 'mpesa-flutter',
    authDomain: 'mpesa-flutter.firebaseapp.com',
    databaseURL: 'https://mpesa-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'mpesa-flutter.appspot.com',
    measurementId: 'G-ZXEGHGZ588',
  );

}